site_name: Это база!
site_url: https://okrasilnikova.github.io/site/
theme:
  name: material
  palette:
    primary: teal
  markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
icon:
    logo: material-memory  
