site_name: Это база!
site_url: https://okrasilnikova.github.io/site/
theme:
  name: material
  palette:
    primary: blue grey
    accent: amber
  markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
icon:
    logo: material-memory  

markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true
params:
  math: true
